print("Program starting.")
word1 = input("Insert first word: ")
word2 = input("Insert second word: ")
length1 = len(word1)
length2 = len(word2)
compound = word1 + word2
print(f"1st word is {length1} characters long.")
print(f"2nd word is {length2} characters long.")
print(f"Words together makes one closed compound '{compound}'.")
print("Program ending.")